### ISSUE TITLE
UOL ol-neu

### ISSUE THREAD

**Issue by nimuelle** [noackorama/ZensusPlugin#11]
wenn ich als root auf "Unizensus-Status" klicke

`Houston, we've got a problem.

    Typ: ParseError
    Nachricht: syntax error, unexpected ')'
    Code: 0
    Stack trace:
    #$ public/plugins_packages/data-quest/UniZensusPlugin/controllers/zensusadmin.php(184)
    #0 vendor/trails/trails.php(152): Trails_Dispatcher->load_controller('zensusadmin')
    #1 vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('zensusadmin/sta...')
    #2 lib/plugins/core/StudIPPlugin.class.php(141): Trails_Dispatcher->dispatch('zensusadmin/sta...')
    #3 public/plugins.php(54): StudIPPlugin->perform('zensusadmin/sta...')
    #4 {main}

`

**Comment by s-at-dq** [comment]
Ist behoben im ol-neu Branch.
