### ISSUE TITLE
Evaluationen färben sich über Nacht wieder rot

### ISSUE THREAD

**Issue by tleilax** [noackorama/ZensusPlugin#4]
Bei uns kam folgendes Ticket rein:

> Fehler, der bereits vor dem Update da war: das Evaluationssymbol ist nach dem Anklicken nicht mehr rot, wird aber über Nacht wieder rot.

Ich weiß leider gar nicht, wo ich da ansetzen könnte/müsste. Könnte das damit zusammenhängen, dass wir den Cache jede Nacht löschen?

**Comment by noackorama** [comment]
Bestimmt, da im cache auch gespeichert wird, wann sich das Ergebnis der xmlrpc Abfrage das letzte mal geändert hat.

**Comment by tleilax** [comment]
Ok. Thx. Dann mach ich den Cronjob erstmal aus und überlege mal, ob wir das irgendwie anders handhaben können. Derweil mach ich dann hier erstmal zu...
